services: 
  - type: web
  name: complete_ecommerce_backend
  env: python
  buildCommand: "./build.sh"
  startCommand: "gunicorn config.wsgi:application"

envVars:
  - key: DATABASE_URL
  fromDatabase: 
    name: ecommerce-db
    property: connectionSting

  - key: SECRET_KEY
    sync: false
  - key: DEBUG
    value: "False"
  - key: ALLOWED_HOSTS
    value: "*"

database:
  - name: ecommerce-db
    databaseName: ecommerce-db